version: "3.9"

services:
  db:
    image: postgres:13.3-alpine
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
  pgadmin4:
    image: 'dpage/pgadmin4:latest'
    container_name: pgadmin4
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
        PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
        PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
  web:
    build: .
    container_name: web
    command: gunicorn english.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./backend/static:/code/static
    depends_on:
      - web
