# Generated by Django 3.2.6 on 2021-08-21 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True, verbose_name='Word')),
                ('transcription', models.CharField(max_length=50, verbose_name='Transcription')),
            ],
            options={
                'verbose_name_plural': 'Dictionary',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=50, verbose_name='Topic name')),
                ('link_to_photo', models.CharField(max_length=150, verbose_name='Link to the photo')),
            ],
            options={
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='TranslationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_type', models.CharField(max_length=50, unique=True, verbose_name='Translation type')),
            ],
            options={
                'verbose_name': 'Translation type',
                'verbose_name_plural': 'Translation types',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50, verbose_name='Unit')),
            ],
            options={
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=50, verbose_name='Translation')),
                ('translation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.translationtype', verbose_name='Translation type')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.dictionary', verbose_name='Word')),
            ],
            options={
                'verbose_name_plural': 'Translation',
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.TextField(max_length=255, verbose_name='Example')),
                ('translation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.translationtype', verbose_name='Translation type')),
            ],
            options={
                'verbose_name_plural': 'Examples',
            },
        ),
        migrations.AddField(
            model_name='dictionary',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.topic', verbose_name='Topic'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.unit', verbose_name='Unit'),
        ),
    ]
