# Generated by Django 3.2.6 on 2021-08-23 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_translation_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='words.dictionary', verbose_name='Word'),
        ),
    ]
