# Generated by Django 3.2.6 on 2021-08-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_alter_translation_word'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name': 'Word', 'verbose_name_plural': 'Dictionary'},
        ),
        migrations.AlterField(
            model_name='topic',
            name='link_to_photo',
            field=models.ImageField(upload_to='', verbose_name='Topic photo'),
        ),
    ]
